# This file was generated by GoReleaser. DO NOT EDIT.
cask "certonid" do
  version "0.10.5"

  on_macos do
    on_intel do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Darwin_x86_64.tar.gz"
      sha256 "cec03a31c5a1e91f36f3997cbbc4d0ad95f939cd85ba7b1e66ecb7e46e62e312"
    end
    on_arm do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Darwin_arm64.tar.gz"
      sha256 "46c96a508f23aa7f95d09336eefdf86a5ae5b7a61ed00e5d983c746995f8b093"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Linux_x86_64.tar.gz"
      sha256 "5407676109c5189bc253c99b79c0da42dbd9d484120e21133c12d660ad796e95"
    end
    on_arm do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Linux_arm64.tar.gz"
      sha256 "8978f70aa9a30697626bae8bc75aa1a698e26368ce80f523afb307f4f9b6f1d7"
    end
  end

  name "certonid"
  desc "Serverless SSH Certificate Authority"
  homepage "https://github.com/certonid/certonid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certonid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certonid"]
    end
  end

  # No zap stanza required

end
