# This file was generated by GoReleaser. DO NOT EDIT.
cask "certonid" do
  version "0.10.5"

  on_macos do
    on_intel do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Darwin_x86_64.tar.gz"
      sha256 "49375a0a29aeca2bb06381040545e62ebd0f557d8962b37b46fedc43743075af"
    end
    on_arm do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Darwin_arm64.tar.gz"
      sha256 "41da1a9a6ba7874d974e2a3a6805a5205d0b4f111f3d2dda60ee636797794fe4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Linux_x86_64.tar.gz"
      sha256 "7f43b2930957e966d83fe6a018104adfeb82eb910da8666585fda66f90b24c15"
    end
    on_arm do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Linux_arm64.tar.gz"
      sha256 "99b94687becbb9d580eb37d3ea91e04e92aa6312b8ba07e4e534e586474e79f8"
    end
  end

  name "certonid"
  desc "Serverless SSH Certificate Authority"
  homepage "https://github.com/certonid/certonid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certonid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certonid"]
    end
  end

  # No zap stanza required

end
