# This file was generated by GoReleaser. DO NOT EDIT.
cask "certonid" do
  name "certonid"
  desc "Serverless SSH Certificate Authority"
  homepage "https://github.com/certonid/certonid"
  version "0.10.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certonid"

  on_macos do
    on_intel do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Darwin_x86_64.tar.gz"
      sha256 "5bebf5d33aa8dff16bc65260a4137471685e88b76eba276b7342f849f2b91122"
    end
    on_arm do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Darwin_arm64.tar.gz"
      sha256 "bcffb2a044120b86fbc9081cfc03787d1b5def7677fd89fbe79392acd7290f8b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Linux_x86_64.tar.gz"
      sha256 "7536062e9e54e8d953e14ae876d2d1efaba0df3cd9490cf4940c41394683366c"
    end
    on_arm do
      url "https://github.com/certonid/certonid/releases/download/#{version}/certonid_Linux_arm64.tar.gz"
      sha256 "6da4f8a7b31433d244af85e52e196b9533faf475fe6194c5d3d326dfd9f157f7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certonid"]
    end
  end

  # No zap stanza required
end
