# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certonid < Formula
  desc "Serverless SSH Certificate Authority"
  homepage "https://github.com/certonid/certonid"
  version "0.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/certonid/certonid/releases/download/0.9.4/certonid_0.9.4_darwin_arm64.tar.gz"
      sha256 "192d8ae3e12c45e64bb22c523ad4cda54a402a91b8897eee2a88e18f737b839c"

      def install
        bin.install "certonid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/certonid/certonid/releases/download/0.9.4/certonid_0.9.4_darwin_x86_64.tar.gz"
      sha256 "31c255d905e01709f7c902ec7227af02cda872b1d56bb77c7224558a4332dfcc"

      def install
        bin.install "certonid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/certonid/certonid/releases/download/0.9.4/certonid_0.9.4_linux_x86_64.tar.gz"
      sha256 "7dce61a4fe377d1d3ce40bc551433bf8eabf303a643efd0e32962e192eb8a074"

      def install
        bin.install "certonid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/certonid/certonid/releases/download/0.9.4/certonid_0.9.4_linux_arm64.tar.gz"
      sha256 "a2c3e726d767742aaa89087f882a3881013ffffbbfc8898c3bc90975782c930d"

      def install
        bin.install "certonid"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/certonid/certonid/releases/download/0.9.4/certonid_0.9.4_linux_arm32.tar.gz"
      sha256 "ac5d45a4a8d8753b6f76e45e1c122669659dc2b9f9174b6ca09bc841e1f74b00"

      def install
        bin.install "certonid"
      end
    end
  end

  test do
    system "#{bin}/certonid", "--version"
  end
end
