# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certonid < Formula
  desc "Serverless SSH Certificate Authority"
  homepage "https://github.com/certonid/certonid"
  version "0.10.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/certonid/certonid/releases/download/0.10.1/certonid_Darwin_x86_64.tar.gz"
      sha256 "a270e82e77d87e2a6d5b7248ea356489a2a0f3490297adced87a31a72c8452a2"

      def install
        bin.install "certonid"
      end
    end
    on_arm do
      url "https://github.com/certonid/certonid/releases/download/0.10.1/certonid_Darwin_arm64.tar.gz"
      sha256 "131b79cb61622e8bc693106ae71bf445d4c1243020ef3195a9caccc87545c4f7"

      def install
        bin.install "certonid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/certonid/certonid/releases/download/0.10.1/certonid_Linux_x86_64.tar.gz"
        sha256 "1c2fed83ace6e83d270e8392e6d6c6b9e63954611d9ae385c8b5eebeba97ed00"

        def install
          bin.install "certonid"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/certonid/certonid/releases/download/0.10.1/certonid_Linux_arm.tar.gz"
        sha256 "c92e1b902cf869de771636e989f6c37fd4cb9bbe6eceecb750976319205f37c6"

        def install
          bin.install "certonid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/certonid/certonid/releases/download/0.10.1/certonid_Linux_arm64.tar.gz"
        sha256 "33e909d5e8b54f229ec902e6de5b30079f1b3649282ec73e58884c83c3dc7d45"

        def install
          bin.install "certonid"
        end
      end
    end
  end

  test do
    system "#{bin}/certonid", "--version"
  end
end
